### ISSUE TITLE
make build error on Centos 7

### ISSUE THREAD

**Issue by jinxmcg** [automaticserver/lxe#10]
When building on Centos 7 I get the following error:
```bash
0.0.0-f6e0603-dirty
<standard input>:1:12: illegal character U+005C '\'
```

the fix is to add **-e**  to the version line in make file:
```bash
@echo -e "package cri\n// Version of LXE\nconst Version = \"$(VERSION)\"" | gofmt > cri/version.go
```

**Comment by dionysius** [comment]
Definitely, thanks for the report! I anyway plan to improve the Makefile a bit
