### ISSUE TITLE
Questions regarding Cilium & LXE

### ISSUE THREAD

**Issue by jinxmcg** [automaticserver/lxe#12]
Hi, 

I was trying to run Cilium for networking and LXE as container images in a k8s cluster, however it seems that the kubelet is only able to run one type of image at the same time, therefore when runing LXE the cilium docker containers are failing to start (cannot pull image)

Are there any workarounds I am not aware of to be able to run/specify the container type?  Would it be able to emulate a docker container image? by using lxc with a docker inside for those types of images? Any ideas?

Thank you

**Comment by dionysius** [comment]
That is correct that LXE can't run OCI images right now (see: https://github.com/automaticserver/lxe/blob/master/doc/development-preview-faq.md#lxd-only-does-system-containers), there is a probability that this is not impossible. It was/is LXD's choice to not offer us these commands.

And yes, kubelet is a singleton per host. You can't run two kubelets on the same machine, that's a limitation of kubelet.

There are several ways to get Cilium into a LXD container, but all those mean that you have to prepare a part:
- Install Cilium during boot of a container using CloudInit (write the cloudconfig to the `container[].Env["user-data"]`)
- Have an LXD image prepared with Cilium preinstalled
- Or use one of the above ways to install docker and let Cilius run on docker inside the LXD container

The last point could be seen a compatibility LXE could offer, but I better try to find a way to run the OCI image directly as a LXD container. And this also feels inefficient to provide a container runtime which just runs docker inside LXD - for that you have already have numerous other container runtimes offering that.

You can also look from another angle: It is not forbidden to run docker alongside LXE. >ou could run the Cilius container manually with docker and let the pods and containers, managed by kubelet, be created using LXE.

**Comment by dionysius** [comment]
By the way, to run lxc containers without lxd, you can use https://github.com/lxc/crio-lxc

**Comment by jinxmcg** [comment]
Thank you. I will look into that as I was not aware of crio-lxc
