### ISSUE TITLE
Does LXE work with LXD3.15?

### ISSUE THREAD

**Issue by magiclamp2** [automaticserver/lxe#2]
LXD is installed using snap on a ubuntu1804 system. encountered error when building LXE. Is my current software version compatible with LXE? how to fix the build error?

$ lxd --version
3.15
$ go version
go version go1.12.6 linux/amd64

Error when build LXE code:
$ make build
0.1.5
/bin/sh: 1: gofmt: not found
Makefile:79: recipe for target 'version' failed
make: *** [version] Error 127

**Comment by tommyknows** [comment]
The `build` step in the makefile also executes the `version` step, which needs `gofmt` to work correctly.

Technically, when installing go, it should also install `gofmt`. 
With normal installations, this can be found in `$GOROOT/bin/gofmt`.

Install `gofmt` / add it to your $PATH and the build should work fine.

However, I noticed something on my mac when building it:
`syscall.SIGPWR` is [not defined](https://github.com/golang/go/issues/1653) on all systems and can thus not be built on macOS.
Just removing the [mentioned](https://github.com/automaticserver/lxe/blob/master/cmd/lxe/main_daemon.go#L81) [lines](https://github.com/automaticserver/lxe/blob/master/cmd/lxe/main_daemon.go#L87)  made it work and shouldn't have a big impact.

**Comment by magiclamp2** [comment]
Thanks for the reply. It was my PATH messed that up. Now I am able to build it but fail because of several repo import. I cannot download those private repos. How should I proceed?

$ make build
0.1.5
go build -v  -o bin/lxe ./cmd/lxe
cmd/lxe/main_daemon.go:11:2: cannot find package "github.com/lxc/lxd/shared/log15" in any of:
	/usr/local/go/src/github.com/lxc/lxd/shared/log15 (from $GOROOT)
	/home/xiaowang/go/src/github.com/lxc/lxd/shared/log15 (from $GOPATH)
cmd/lxe/main.go:8:2: cannot find package "github.com/lxc/lxd/shared/logger" in any of:
	/usr/local/go/src/github.com/lxc/lxd/shared/logger (from $GOROOT)
	/home/xiaowang/go/src/github.com/lxc/lxd/shared/logger (from $GOPATH)
cmd/lxe/main.go:9:2: cannot find package "github.com/lxc/lxd/shared/logging" in any of:
	/usr/local/go/src/github.com/lxc/lxd/shared/logging (from $GOROOT)
	/home/xiaowang/go/src/github.com/lxc/lxd/shared/logging (from $GOPATH)
cmd/lxe/main.go:10:2: cannot find package "github.com/lxc/lxe/cri" in any of:
	/usr/local/go/src/github.com/lxc/lxe/cri (from $GOROOT)
	/home/xiaowang/go/src/github.com/lxc/lxe/cri (from $GOPATH)
cmd/lxe/main.go:11:2: cannot find package "github.com/lxc/lxe/shared" in any of:
	/usr/local/go/src/github.com/lxc/lxe/shared (from $GOROOT)
	/home/xiaowang/go/src/github.com/lxc/lxe/shared (from $GOPATH)
Makefile:20: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by tommyknows** [comment]
I suspect that you have cloned this repository into your `$GOPATH` somewhere and go is thus not using modules for this build. You can use modules for this build by setting `GO111MODULE=on`:
```
env GO111MODULE=on make build
0.1.5-dirty
go build -v  -o bin/lxe ./cmd/lxe
github.com/lxc/lxe/shared
github.com/lxc/lxe/lxf/device
github.com/lxc/lxe/network
github.com/lxc/lxe/lxf/lxo
github.com/lxc/lxe/lxf
github.com/lxc/lxe/cri
github.com/lxc/lxe/cmd/lxe
```

You could also move the project out of the `$GOPATH` if you want to, this should fix it too.

**Comment by magiclamp2** [comment]
Hello I am still having troubles building.(Sorry I am not familair with golang) I re-installed golang to 12.7 and now could not find the uuid package no matter I cloned into $GOPATH or not. Any advise? 

`~/lxe$ env GO111MODULE=on make build
0.1.5
go build -v  -o bin/lxe ./cmd/lxe
go: finding github.com/google/uuid v1.0.0
go: github.com/google/uuid@v1.0.0: unknown revision v1.0.0
go: error loading module requirements
Makefile:20: recipe for target 'build' failed
make: *** [build] Error 1`

**Comment by tommyknows** [comment]
the same command is working for me just fine.
can you try these two things:
- run `go clean -modcache` and try to build it again. if that should not work, try:
- run `go get github.com/google/uid@v1.0.0` and print the output

**Comment by magiclamp2** [comment]
Same issue with manual get. Only way I can get is from $GOROOT. Also, very strange that always tries to get v1.0.0

`~/lxe$ go clean -modcache
go: finding github.com/google/uuid v1.0.0
go: github.com/google/uuid@v1.0.0: unknown revision v1.0.0
go: error loading module requirements

~/lxe$ go get github.com/google/uid@v1.0.0
go: finding github.com/google/uuid v1.0.0
go: github.com/google/uuid@v1.0.0: unknown revision v1.0.0
go: error loading module requirements

~/lxe$ go get github.com/google/uid@v1.1.0
go: finding github.com/google/uuid v1.0.0
go: github.com/google/uuid@v1.0.0: unknown revision v1.0.0
go: error loading module requirements`

**Comment by tommyknows** [comment]
Can you print the output of `go env`? 
It sounds to me like some config issue, but I can't say what exactly.

Also, please try running the `go get github.com/google/uuid@v1.0.0` (i made a typo in the link on my other post, sorry) in the git-repository as well as somewhere else (on your desktop for example).

**Comment by magiclamp2** [comment]
I agree, very likely a config issue. output pasted blow. Please advice:)
For uuid package, the result is the same as the one with typo(unknow revision). 

~/lxe$ go env
GOARCH="amd64" 
GOBIN=""
GOCACHE="/home/xiao/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xiao/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/xiao/lxe/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build528541404=/tmp/go-build -gno-record-gcc-switches"

**Comment by tommyknows** [comment]
Sorry for the delay.
Very strange issues. Do you have some git URL-rewrite rules? 
If it's not that, then i'm clueless. Can you `go get` any other package?

**Comment by magiclamp2** [comment]
Don't worry it worked on an different system. But ran into a different issue ...restarting kubelet still complains unable to connect docker although args passed to both `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` and `/etc/default/kubelet`. worth starting a new issue?
