### ISSUE TITLE
lxc pods are not completely cleaned up by kubectl delete deployment command

### ISSUE THREAD

**Issue by psamadda** [automaticserver/lxe#20]
If we run the following command to create the deployment, we can view that the pods are up with lxc containers.
_kubetcl apply -f Deployment.yaml_
 If we run the following command to remove the deployment, the deployment is cleaned up.
_kubectl delete deployment <deployment name>_
But if we run the following command to view the existing containers inside the node, we can see that the container(which was created at the time of deployment) is in STOPPED state. So it is not cleaned up completely during kubectl delete deployment step.
_lxc list_
Another issue that I have faced is that though I am using remote lxc image server to create the container still it is downloading the image inside the node and storing it.

**Comment by dionysius** [comment]
This is not an issue of lxe. Kubelet decides itself when to delete the container and podsandbox, same goes for the image. These are the CRI Methods:
- https://github.com/kubernetes/cri-api/blob/e2c193f96f26a9c71f1922090bd99e0889cea6ca/pkg/apis/runtime/v1/api.proto#L55
- https://github.com/kubernetes/cri-api/blob/e2c193f96f26a9c71f1922090bd99e0889cea6ca/pkg/apis/runtime/v1/api.proto#L76

LXE logs all called methods in loglevel debug.
