### ISSUE TITLE
Accessing nfs share from lxc container inside k3s cluster

### ISSUE THREAD

**Issue by psamadda** [automaticserver/lxe#21]
I have successfully deployed lxc container in k3s cluster. Now I want to configure lxc container to act as nfs client with rw permission in nfs share. The nfs share mount is configured with rw permission but actually it gets read permission. Using docker the requirement is tested successfully. Is there any way that I can access rw permission in a common location from all lxc container?

<img width="701" alt="Screenshot (75)" src="https://user-images.githubusercontent.com/5486203/185406613-4bfcbe1e-a433-431a-a9c6-d6b4ed59921a.png">
<img width="894" alt="Screenshot (76)" src="https://user-images.githubusercontent.com/5486203/185406653-08d7e7ef-ce62-4bd4-9db2-017e4975b4ef.png">

**Comment by dionysius** [comment]
I haven't yet assigned a PVC to a container. I know that kubelet manages the mounts and sends instructions to lxe via CRI. LXE doesn't do much except forwarding those mount instructions to lxd.

1) Can you paste the container config with `lxc config show ... --expanded`? So we can see what lxe has configured the mount to look like.
2) Can you paste the permissions of the folder in `source` of the above command with `ls -lah ...`? This is the folder kubelet created and maybe we run into a uid/gid mismatch.
3) Do you have the same issues with `EmptyDir`? https://kubernetes.io/docs/concepts/storage/volumes/#emptydir. And repeat the container config command from 1) and folder permissions from 2) so we can compare the mount instructions.

I won't be able to reproduce it within 2 weeks as I'm on holiday.

**Comment by dionysius** [comment]
Has been over a year now without further comments. Feel free to open a new issue if this still persists
