### ISSUE TITLE
LXD DEBS & PPA

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [automaticserver/lxe#26]
https://github.com/randombenj/lxd-deb

https://launchpad.net/~randombenj/+archive/ubuntu/lxd

sudo add-apt-repository ppa:randombenj/lxd
sudo apt update
sudo apt install lxd

Due to so many issues using snap, that made lxd nearly unusable for us we decided to package lxd as a debian package, inspired by: https://salsa.debian.org/mjeanson/lxd

The dependencies are installed using vendoring and uploaded as a source package to ubuntu ppa. This is mainly to avoid having to deal with outdated golang versions on ubuntu.

The following packages are built:

lxd: Contains the lxd daemon (depends on all the other packages)
lxd-client: Contains the lxc client command
lxd-agent: Optional lxd-agent used inside the virtual machines
libdqlite0: Used internally by lxd
libraft2: Used by libdqlite0

**Comment by dionysius** [comment]
It took a while but debian finally has also an lxd source package and since the bookworm release available stable

- https://wiki.debian.org/LXD
- https://salsa.debian.org/go-team/packages/lxd

Backporting is difficult though as they packaged every single dependency. But if bookworm fits your case, I'd go with that one.

**Comment by OpenOS-Project-Creator-Founder** [comment]
https://github.com/f-bn/lxd-images/issues/3

Would LXE be able to be integrated into something like this?

**Comment by dionysius** [comment]
I don't know if I understand the question. The repo you linked has manifests for custom images for LXD using distrobuilder. Definitely you can already use custom images with LXE:

- Build your custom image with distrobuilder
- Upload it to your lxd registry
- [Register this registry](https://linuxcontainers.org/lxd/docs/master/reference/remote_image_servers/#remote-image-servers) on your lxd
- From then you can use this image in your podspec with `registryname/imagename`
