### ISSUE TITLE
Failed to start container

### ISSUE THREAD

**Issue by htbase** [automaticserver/lxe#3]
Hi there

When we have K8s create the container, we get the following error:

 Warning  Failed     0s    kubelet, ip-172-31-35-162  Error: Failed to run: /snap/lxd/current/bin/lxd forkstart ubuntu /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/ubuntu/lxc.conf:

Here is the yaml file I am using:

 apiVersion: v1
 kind: Pod
 metadata:
   name: os
   labels:
     app: os
 spec:
   containers:
     - name: ubuntu
       image: ubuntu/14.04

If I check lxc, I can see it successfully downloaded the image and tried to create the container, but failed on starting it

Only thing I see in the lxe.log file is the following:

t=2019-07-27T19:54:29+0000 lvl=eror msg="StartContainer: ContainerID usl24jpixjqd7rpi trying to start container: Failed to run: /snap/lxd/current/bin/lxd forkstart usl24jpixjqd7rpi /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/usl24jpixjqd7rpi/lxc.conf: " 

Any ideas?

Thanks!

**Comment by htbase** [comment]
Hi there

I'm still having the same issue

Having you see this problem? Any ideas?

Thanks!

**Comment by dionysius** [comment]
Your second post about "failed to get device for dir" is an error yes, but it's not related to your initial issue. We would need to move that into another issue.

Since forkstart threw the error, have a look into `/var/log/lxd/<containerid>/` (or where the snap's lxd equivalent lies) and look if you can find the error there (usually in `lxd.log`, but have also a look into `forkstart.log`). Maybe its helpful to also post the `lxc.conf`.

**Comment by htbase** [comment]
Thank you for t he response.

Here is what I found in the container log:

lxc fmoabzfe5lcm7w7i 20190728222653.223 ERROR    network - network.c:lxc_setup_netdev_in_child_namespaces:3705 - Operation not permitted - Failed to rename network device "vethMD3YIV" to "eth0"
lxc fmoabzfe5lcm7w7i 20190728222653.223 ERROR    network - network.c:lxc_setup_network_in_child_namespaces:3892 - Failed to setup netdev
lxc fmoabzfe5lcm7w7i 20190728222653.223 ERROR    conf - conf.c:lxc_setup:3570 - Failed to setup network
lxc fmoabzfe5lcm7w7i 20190728222653.223 ERROR    start - start.c:do_start:1321 - Failed to setup container "fmoabzfe5lcm7w7i"
lxc fmoabzfe5lcm7w7i 20190728222653.223 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 5)
lxc fmoabzfe5lcm7w7i 20190728222653.286 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:873 - Received container state "ABORTING" instead of "RUNNING"
lxc fmoabzfe5lcm7w7i 20190728222653.287 ERROR    start - start.c:__lxc_start:2039 - Failed to spawn container "fmoabzfe5lcm7w7i"


Also, here is the content of the lxc.conf

lxc.log.file = /var/snap/lxd/common/lxd/logs/fmoabzfe5lcm7w7i/lxc.log
lxc.log.level = warn
lxc.console.buffer.size = auto
lxc.console.size = auto
lxc.console.logfile = /var/snap/lxd/common/lxd/logs/fmoabzfe5lcm7w7i/console.log
lxc.mount.auto = proc:rw sys:rw
lxc.autodev = 1
lxc.pty.max = 1024
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional 0 0
lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file,optional 0 0
lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none rbind,create=dir,optional 0 0
lxc.mount.entry = /sys/kernel/security sys/kernel/security none rbind,create=dir,optional 0 0
lxc.mount.entry = /dev/mqueue dev/mqueue none rbind,create=dir,optional 0 0
lxc.include = /snap/lxd/current/lxc/config//common.conf.d/
lxc.arch = linux64
lxc.hook.version = 1
lxc.hook.pre-start = /proc/1763/exe callhook /var/snap/lxd/common/lxd 3 start
lxc.hook.stop = /snap/lxd/current/bin/lxd callhook /var/snap/lxd/common/lxd 3 stopns
lxc.hook.post-stop = /snap/lxd/current/bin/lxd callhook /var/snap/lxd/common/lxd 3 stop
lxc.tty.max = 0
lxc.uts.name = fmoabzfe5lcm7w7i
lxc.mount.entry = /var/snap/lxd/common/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.apparmor.profile = lxd-fmoabzfe5lcm7w7i_</var/snap/lxd/common/lxd>//&:lxd-fmoabzfe5lcm7w7i_<var-snap-lxd-common-lxd>:
lxc.seccomp.profile = /var/snap/lxd/common/lxd/security/seccomp/fmoabzfe5lcm7w7i
lxc.idmap = u 0 1000000 1000000000
lxc.idmap = g 0 1000000 1000000000
lxc.environment = KUBERNETES_PORT_443_TCP_PORT=443
lxc.environment = KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
lxc.environment = KUBERNETES_SERVICE_PORT_HTTPS=443
lxc.environment = KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
lxc.environment = KUBERNETES_PORT_443_TCP_PROTO=tcp
lxc.environment = KUBERNETES_SERVICE_PORT=443
lxc.environment = KUBERNETES_SERVICE_HOST=10.96.0.1
lxc.environment = KUBERNETES_PORT=tcp://10.96.0.1:443
lxc.rootfs.path = dir:/var/snap/lxd/common/lxd/containers/fmoabzfe5lcm7w7i/rootfs
lxc.mount.entry = /var/snap/lxd/common/lxd/devices/fmoabzfe5lcm7w7i/disk.disk--dev-termination-log.dev-termination-log dev/termination-log none bind,create=file 0 0
lxc.mount.entry = /var/snap/lxd/common/lxd/devices/fmoabzfe5lcm7w7i/disk.disk--etc-hosts.etc-hosts etc/hosts none bind,create=file 0 0
lxc.mount.entry = /var/snap/lxd/common/lxd/devices/fmoabzfe5lcm7w7i/disk.disk--mnt-secrets-kubernetes.io-serviceaccount.mnt-secrets-kubernetes.io-serviceaccount mnt/secrets/kubernetes.io/serviceaccount none bind,ro,create=dir 0 0
lxc.net.0.type = veth
lxc.net.0.script.up = /proc/1763/exe callhook /var/snap/lxd/common/lxd 3 network-up eth0
lxc.net.0.flags = up
lxc.net.0.link = lxdbr0
lxc.net.0.hwaddr = 00:16:3e:d7:15:a7
lxc.net.0.name = eth0
lxc.net.1.type = veth
lxc.net.1.script.up = /proc/1763/exe callhook /var/snap/lxd/common/lxd 3 network-up nic-eth0
lxc.net.1.flags = up
lxc.net.1.link = lxebr0
lxc.net.1.hwaddr = 00:16:3e:a2:56:64
lxc.net.1.name = eth0
lxc.mount.auto = shmounts:/var/snap/lxd/common/lxd/shmounts/fmoabzfe5lcm7w7i:/dev/.lxd-mounts


Seems like it fails trying to rename the network?

**Comment by htbase** [comment]
I found the issue was my profile configuration. 

I removed the interface name and it worked

Thanks!
