### ISSUE TITLE
Service discovery in lxe

### ISSUE THREAD

**Issue by pmajum** [automaticserver/lxe#6]
I have to run two pods with lxc container and needs to communicate between those how to do that?

**Comment by dionysius** [comment]
Are we talking about service discovery itself, meaning obtaining endpoint addresses? (see [environment variables](https://github.com/automaticserver/lxe/blob/master/doc/development-preview-faq.md#environment-variables)
> Environment variables defined in the ContainerSpec of the PodSpec are passed to the lxd container config as `config.environment.*`, which are passed to the init process of the container (see `cat /proc/1/environ`) and usually the init system does not forward these. [...]
```
# xargs -0 -n 1 echo < /proc/1/environ
[...]
KUBERNETES_SERVICE_HOST=192.168.24.1
KUBERNETES_PORT_443_TCP_ADDR=192.168.24.1
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP=tcp://192.168.24.1:443
KUBERNETES_PORT=tcp://192.168.24.1:443
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_HTTPS=443
container=lxc
```

If we're talking about same node communication between pods, this should work out of the box thanks to the lxd networking (or CNI if you set `--network-plugin=cni`). If not, we have to figure out how the interfaces are looking right now

If we're talking about inter node communication, we have to consider the [kubernetes network plugin](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/) you are using.

**Comment by shubhparekh** [comment]
Can we call service running inside lxc container through clusterip based dns and port of kubernetes service? and also expose it externally through nodeport?

**Comment by dionysius** [comment]
Yes, pods created with lxe can be called through clusterip

The main part is network configuration here. Besides kubelet and lxe you need the networking tools of your chosen network plugin. I only have experience with flannel+kubeproxy, but I think the other kubernetes network plugins work similiar. Your used network plugin decides how your pod interface should look like and maybe they provide a CNI conf, so you can hook that up with lxe `--network-plugin=cni`. Or, like flannel, your plugin chooses a network range for your node, you can set that in lxe with `--bridge-dhcp-range`.
>       --bridge-dhcp-range string    Which DHCP range to configure in the 'lxebr0' lxd bridge. Only applies if network-plugin is set to '' and does not exist yet. If empty, uses random range provided by lxd. Not needed, if kubernetes will publish the range using CRI UpdateRuntimeconfig

Yes, pods can be reached with Nodeport. LXE uses LXD's proxy device for that.

But: I have not played with all the network plugins! I only know flannel+kube-proxy and kube-router so far.

**Comment by dionysius** [comment]
feel free to reopen if something is missing
